CONFIGURATOR_TYPE_LINE = 'Line'
CONFIGURATOR_TYPE_CURVE = 'Curve'
CONFIGURATOR_TYPE_LINEMOVE = 'Line move'
CONFIGURATOR_TYPE_LINEFIXEDMOVE = 'Fixed move of line'
CONFIGURATOR_TYPE_LINEBYCURVE = 'Line by curve'
CONFIGURATOR_TYPE_ROTATE_SURFACE = 'Rotate surface'
CONFIGURATOR_TYPE_PLANE = 'Plane'
CONFIGURATOR_TYPES = [CONFIGURATOR_TYPE_LINE, CONFIGURATOR_TYPE_CURVE, CONFIGURATOR_TYPE_LINEMOVE,
                      CONFIGURATOR_TYPE_LINEBYCURVE, CONFIGURATOR_TYPE_LINEFIXEDMOVE, CONFIGURATOR_TYPE_ROTATE_SURFACE, CONFIGURATOR_TYPE_PLANE]