CONFIGURATOR_TYPE_LINE = 'Line'
CONFIGURATOR_TYPE_CURVE = 'Curve'
CONFIGURATOR_TYPE_CYLINDRICAL_SURFACE = 'Cylindrical Surface'
CONFIGURATOR_TYPE_CONICAL_SURFACE = 'Conical Surface'
CONFIGURATOR_TYPE_ROTATE_SURFACE = 'Rotational Surface'
CONFIGURATOR_TYPE_PLANE = 'Plane'
CONFIGURATOR_TYPES = [CONFIGURATOR_TYPE_LINE, CONFIGURATOR_TYPE_CURVE, CONFIGURATOR_TYPE_CYLINDRICAL_SURFACE,
                      CONFIGURATOR_TYPE_CONICAL_SURFACE, CONFIGURATOR_TYPE_ROTATE_SURFACE, CONFIGURATOR_TYPE_PLANE]